### PR TITLE
Feature/improve ci coverage

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma/issues/46

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis I upgraded dependencies version, could you please have a look once you are ok, I will proceed with tests fixing

**Comment by opoudjis** [comment]
As already noted, I don't know where this gem has come from and what it's for, so I can't comment on it from a business perspective.

**Comment by opoudjis** [comment]
This is code I never interacted with, and which therefore has not been kept up to date. I see that @CAMOBAP795 has aligned it with subsequent refactoring of the Metanorma stack. I am impressed!

**Comment by opoudjis** [comment]
@ronaldtse should still review this; in particular, because this has been refactored to now depend on Standoc, like all other gems (but for GB > ISO), rather than RSD.

**Comment by CAMOBAP795** [comment]
@ronaldtse could you please review

**Comment by ronaldtse** [comment]
@CAMOBAP795 great work!

Most of the spec errors are due to XML comparison -- we should use something like "equivalent_xml" in rspec to compare XML syntax.

But there is one real error in functionality. In https://travis-ci.com/metanorma/metanorma-vsd/jobs/192705499#L2864-L2887 :

```
       -<div id="I">
        -   <h2>3.1. Normal Terms</h2>
        -   <p class="TermNum" id="J">3.1.1</p>
        -   <p class="Terms" style="text-align:left;">Term2</p>
        +<p>ISO and IEC maintain terminological databases for use in
        +standardization at the following addresses:</p>
         
        - </div><div id="K"><h2>3.2. Symbols and abbreviated terms</h2>
        -   <dl><dt><p>Symbol</p></dt><dd>Definition</dd></dl>
        - </div></div>
        +<ul>
        +<li> <p>ISO Online browsing platform: available at
        +  <a href="http://www.iso.org/obp">http://www.iso.org/obp</a></p> </li>
        +<li> <p>IEC Electropedia: available at
        +  <a href="http://www.electropedia.org">http://www.electropedia.org</a>
        +</p> </li> </ul>
        +<div id="I"><h2>3.1. Normal Terms</h2>
        +
        +     <p class="TermNum" id="J">3.1.1.</p>
        +     <p class="Terms" style="text-align:left;">Term2</p>
        +
        +   </div><div id="K"><h2>3.2. Symbols and abbreviated terms</h2>
        +     <dl><dt><p>Symbol</p></dt><dd>Definition</dd></dl>
        +   </div></div>
```

As you can see, ISO and IEC terms should not be inherited here in VSD. In fact, they should be applied in `metanorma-iso`, not in `metanorma-standoc`.

This phrase is given by the `isodoc` gem (https://github.com/metanorma/isodoc/blob/07b5e775a99415add74ea75c1cea500bae8d96bd/lib/isodoc-yaml/i18n-en.yaml).

I suspect that this is a carryover from when `metanorma-standoc` was extracted from `metanorma-iso`. Can @opoudjis confirm this? The code for:

```
        +<li> <p>**ISO Online browsing platform**: available at
        +  <a href="http://www.iso.org/obp">http://www.iso.org/obp</a></p> </li>
        +<li> <p>IEC Electropedia: available at
        +  <a href="http://www.electropedia.org">http://www.electropedia.org</a>
```

Should be moved to `metanorma-iso`.

**Comment by opoudjis** [comment]
Since I have no idea what this gem is even for, I'm disinclined to respond. Yes, you have already assigned yet another ticket to remove this from standoc.

**Comment by ronaldtse** [comment]
Echoing the above comments, it wasn't `metanorma-standoc` at fault but the spec failures are caused by the `isodoc` gem instead (https://github.com/metanorma/isodoc/issues/94).

**Comment by ronaldtse** [comment]
Merging this first, the spec failure now to be done in #3.

**Pull request merged**
